In [1]:
import pandas as pd

In [2]:

df = pd.read_csv('C:/Users/Alankar Mali/OneDrive/Desktop/DATA ENGLINEERING_2026/PYTHON REVISION/customer_shopping_behavior.csv')

In [3]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
df.describe()  #use for statistics

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df.describe(include='all') #shows all columns works only for numerical values

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

* df.isnull() to check null
* df.isnull().sum() to count total null in each field
* df.isnull().any() to check null present or not 
* df.isnull().sum().sum() check total null
* df.notnull() opposite of df.isnull

In [ ]:
df.isnull().sum() 
# there are 37 null values in review rating feild

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64


* WE USE MEDIAN OVER MEAN BEACUSE Value that is low or high as compared to others.
Outlier = “value that is unusually high or low compared to others”
example = [10,12,13,12,11,100]
100 is outlier so we choose mean

* in short meadian is not affected by outliers. but mean does.

In [11]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [ ]:
df.isnull().sum() #as we can see all nulls filled by median.

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
Reviwe Rating             0
dtype: int64

In [6]:
#df.columns = df.columns.str.lower().str.replace(' ','_')
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [7]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [ ]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [5]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

* CREATE A COLUMN AGE_GROUP 
- use this command to divide the column age according to the their age.
-  " df['age_group']=pd.qcut(df['age], q=4, labels = lables, duplicates='drop')"

In [8]:
labels = ['young_adult','adult','middle_age','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [9]:
df[['age','age_group']].head()

   age    age_group
0   55   middle_age
1   19  young_adult
2   50   middle_age
3   21  young_adult
4   45   middle_age

- To select a fixed range then use 
- pd.cut(df['column_name'], bins= bins_youassign, labels=lables_youassign)
- bins divide data into ranges

In [10]:
labels1 = ['baby','young_adult','adult','middle_age','senior']
bins = [0,7,18,26,50,100]
df['age_group1'] = pd.cut(df['age'], bins = bins , labels=labels1)

In [11]:
df[['age','age_group1']].head()

   age  age_group1
0   55      senior
1   19       adult
2   50  middle_age
3   21       adult
4   45  middle_age

In [13]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,age_group1
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle_age,senior
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young_adult,adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle_age,middle_age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult,adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle_age,middle_age

latest modification

df=df.drop(columns=['colmun_name']) - to drop column

df.drop(index=1) - to drop row 

df.drop(index=[1,2,3]) - to drop multiple rows

df.dropna() - to drop NaN values and rows where they are present

df.dropna(subset=['age']) - to drop NaN values by specifing column and drop row 

df.dropna(axis=1) -  drop column if Nan value is present

In [ ]:
df = df.drop(columns=['age_group1'])

In [16]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle_age
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young_adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle_age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle_age

#create column purchase_frequecy_days

In [35]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [48]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Annually': 365 or 366,
    'Quarterly': 90,
    'Bi-Weekly': 60,
    'Monthly': 30,
    'Every 3 Months': 90
}
df['purchase_frequency_Days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [49]:
df[['purchase_frequency_Days','frequency_of_purchases']].head(15)

    purchase_frequency_Days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       60              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly

In [50]:
df.isnull().sum()

customer_id                 0
age                         0
gender                      0
item_purchased              0
category                    0
purchase_amount_(usd)       0
location                    0
size                        0
color                       0
season                      0
review_rating              37
subscription_status         0
shipping_type               0
discount_applied            0
promo_code_used             0
previous_purchases          0
payment_method              0
frequency_of_purchases      0
age_group1                  0
age_group                   0
purchase_frequency_Days     0
dtype: int64

In [51]:
df['review_rating'] = df['review_rating'].transform(lambda x:x.fillna(x.median()))

In [ ]:
df['column_name']= df['column_name'].transform(lambda x:x.fillna(x.median()))

In [52]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group1                 0
age_group                  0
purchase_frequency_Days    0
dtype: int64

#we are going to check if the columns are redundant or not.
#because if both have same input and want to eleminate one of them.

In [54]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [ ]:
#df['discount_applied'] == df['promo_code_used']
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [58]:
df = df.drop('promo_code_used', axis=1)

In [59]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group1', 'age_group',
       'purchase_frequency_Days'],
      dtype='object')

------------------------------------------------------

* HERE WE ARE GOING TO ESTABLISH A CONNECTION BETWEEN VS STUDIO PTHON NOTBOOK OR ANY SOURCE LIKE JUPYTER WITH MYSQL OR POSTGRES OR ANY DESTINATIONS.

* 1ST- INSTALL sqlalchemy pymysql for mysql (pip install sqlalchemy pymysql)
and - for postgres pip install psycopg2-binary sqlalchemy
and - for SQL SERVER pip install pyodbc sqlalchemy
* 2nd- from sqlalchemy import create_engine

In [ ]:
pip install sqlalchemy pymysql  #!pip install sqlalchemy pymysql

Collecting sqlalchemyNote: you may need to restart the kernel to use updated packages.

  Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 2.5 MB/s eta 0:00:00
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
     ---------------------------------------- 45.3/45.3 KB 2.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\alankar mali\onedrive\desktop\data englineering_2026\python revision\pr-venvnew\lib\site-packages (from sqlalchemy) (4.15.0)
Collecting greenlet>=1
  Downloading greenlet-3.3.2-cp310-cp310-win_amd64.whl (230 kB)
     -------------------------------------- 230.1/230.1 KB 3.5 MB/s eta 0:00:00
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 pymysql-1.1.2 sqlalchemy-2.0.49

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\Alankar Mali\OneDrive\Desktop\DATA ENGLINEERING_2026\PYTHON REVISION\pr-venvnew\Scripts\python.exe -m pip install --upgrade pip' command.

In [61]:
from sqlalchemy import create_engine

* USE THIS CODE TO MAKE A CONNECTION.
* engine  = create_engine(f"mysql+pymysql://{username}:{password}@{localhost}/{database}") for mysql
* engine  = create_engine(f"mysql+pymysql://{username}:{password}@{localhost}:{port}/{database}") for postgres

HERE WE HAVE MAP TABLE TO SQL DATABASE.

In [67]:
username = 'root'
password = 'alankar'
localhost = 'localhost'
port = 3306
database = 'data_analyst'

engine  = create_engine(f"mysql+pymysql://{username}:{password}@{localhost}/{database}")

table_name = 'customer'
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"data successfully loaded into table {table_name} in database {database}.")

data successfully loaded into table customer in database data_analyst.